---
title: "Test iNEXT"
author: "Paolo Cozzi"
date: today
toc: true
number-sections: true
format:
  html:
    code-line-numbers: true
    html-math-method: katex
    df-print: paged
    code-fold: true
    toc-depth: 4
editor: source
---

```{r setup}
#| label: setup
#| output: false
library(here)
library(ggplot2)
library(iNEXT)
library(targets)
library(dplyr)

store_path <- here::here("_targets")
```

load coverage data

```{r load-coverage}
#| label: load-coverage
tar_load(coverage_stats, store = store_path)
```

load the combined graph

```{r load-combined}
#| label: load-combined
tar_load(combined_iNEXT_results, store = store_path)
```

create a plot 

```{r plot-combined}
#| label: plot-combined
#| fig-width: 10
#| fig-height: 8
min_sequences <- min(coverage_stats$n_seqs)

# Define custom linetypes
custom_linetypes <- c("Rarefaction" = "solid", "Extrapolation" = "dashed", "Observerd" = "dotdashed")

ggplot(combined_iNEXT_results, aes(x = x, y = y, color = Assemblage, linetype = Method)) +
  geom_line(linewidth = 1) +  # Plot the lines
  geom_ribbon(aes(ymin = y.lwr, ymax = y.upr, fill = Assemblage), alpha = 0.2, color = NA) +  # Add confidence intervals
  geom_vline(xintercept = min_sequences, linetype = "dashed", color = "red") +  # Add vertical line
  scale_linetype_manual(values = custom_linetypes) +  # Set custom linetypes
  labs(
    title = "Rarefaction and Extrapolation Curves",
    x = "Sample Size",
    y = "Diversity Estimate"
  ) +
  theme_bw()
```

Try to extract rarefaction data:

```{r extract-rarefaction}
#| label: extract-rarefaction

# Extract the size_based data frame
size_based_data <- combined_iNEXT_results$iNextEst$size_based

# Filter for interpolated (rarefaction) values
rarefaction_data <- size_based_data %>%
  filter(Method == "Rarefaction")

# View the filtered data
head(rarefaction_data)
```

Time to make a plot

```{r plot-rarefaction}
#| label: plot-rarefaction
#| fig-width: 10
#| fig-height: 8
#| fig-caption: "Rarefaction curves"

# Create the plot
ggplot(rarefaction_data, aes(x = m, y = qD, color = Assemblage)) +
  geom_line(linewidth = 1) +  # Plot the lines
  geom_ribbon(aes(ymin = qD.LCL, ymax = qD.UCL, fill = Assemblage), alpha = 0.2, color = NA) +  # Add confidence intervals
  geom_vline(xintercept = min_sequences, linetype = "dashed", color = "red") +  # Add vertical line
  labs(
    title = "Rarefaction Curves",
    x = "Sample Size",
    y = "Diversity Estimate"
  ) +
  theme_bw()
```

here's the rarefaction curve made with `vegan`

```{r vegan-rarefaction}
#| label: vegan-rarefaction
#| fig-width: 10
#| fig-height: 8
#| fig-caption: "Rarefaction curves with vegan"
tar_load(rarecurve_df, store = store_path)

min_sequences <- min(coverage_stats$n_seqs)

ggplot(rarecurve_df, aes(x = Sample, y = Species, color = Site)) +
  geom_line() +
  geom_vline(xintercept = min_sequences, linetype = "dashed", color = "red") +  # Add vertical line
  labs(
    title = "Rarefaction Curves for All Samples",
    x = "Number of Individuals Sampled",
    y = "Number of Species Observed"
  ) +
  theme_bw()
```
